Fixed the mystery token error.
Ok, learned something. This error:

    Error: There's already a token with the same name, '=' in this fbt call. Use fbt.sameParam if you want to reuse the same token value or give this token a different name

is caused by having more than one `<br />` inside the `<fbt>` tag. Don't understand it, but there you are.