Localize DApp2 (#1802)
* removing dapp1 translations and rerunning translations

* Crowdin translation pipeline minimally working.

Notes added to README.md

* Prettier

* Fixing file name

* Wrap strings for components

* prettier

* commit all-messages.json

* prettier

* First batch of listing creation wrapping. Has error.

* Wrappin', wrappin, wrappin

* Prettier

* Fixed the mystery token error.

Ok, learned something. This error:

    Error: There's already a token with the same name, '=' in this fbt call. Use fbt.sameParam if you want to reuse the same token value or give this token a different name

is caused by having more than one `<br />` inside the `<fbt>` tag. Don't understand it, but there you are.

* done with pages/transaction

* prettier

* linter

* Wrap settings for translation

* Catch a vanilla case

* wrapping

* more wrap

* wrap

* Handle document titles

* more wrapping, plus hourly pricing display fix

* wrapping and hourly price fix

* Merge upstream changes

* Wrap messaging for translation

* fixes

* prettier

* Missing messages

* remove duplicate fbt include

* Localize category and subcategories in listing create

* wrap

* wrap

* starting tag param l10n sweep

* S&R fix for l10n of `children=` and `tooltip=`

* Appease lint

* More param l10n catches

* wrapping little misses

* little fixes and checks for chinese

* forgot fbt

* Undo overzealous fbt in dapp creator...

* Undo overzealous fbt leaked into admin

* removing dapp1 translations and rerunning translations

* Crowdin translation pipeline minimally working.

Notes added to README.md

* Fixing file name

* Wrap strings for components

* commit all-messages.json

* done with pages/transaction

* prettier

* linter

* Wrap settings for translation

* Catch a vanilla case

* wrapping

* more wrap

* wrap

* Handle document titles

* more wrapping, plus hourly pricing display fix

* wrapping and hourly price fix

* Merge upstream changes

* Wrap messaging for translation

* fixes

* prettier

* Missing messages

* onboarding pages

* tweaks