Stan/hard core wrapping (#1801)
* removing dapp1 translations and rerunning translations

* Crowdin translation pipeline minimally working.

Notes added to README.md

* Prettier

* Fixing file name

* Wrap strings for components

* prettier

* commit all-messages.json

* prettier

* First batch of listing creation wrapping. Has error.

* Wrappin', wrappin, wrappin

* Prettier

* Fixed the mystery token error.

Ok, learned something. This error:

    Error: There's already a token with the same name, '=' in this fbt call. Use fbt.sameParam if you want to reuse the same token value or give this token a different name

is caused by having more than one `<br />` inside the `<fbt>` tag. Don't understand it, but there you are.